# Generated by Django 5.1.5 on 2025-01-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cognom1', models.CharField(max_length=50)),
                ('cognom2', models.CharField(max_length=50)),
                ('correu', models.EmailField(max_length=254)),
                ('curs', models.CharField(max_length=10)),
                ('moduls_matriculats', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cognom1', models.CharField(max_length=50)),
                ('cognom2', models.CharField(max_length=50)),
                ('correu', models.EmailField(max_length=254)),
                ('curs', models.CharField(max_length=10)),
                ('tutor', models.BooleanField(default=False)),
                ('moduls_imparteix', models.TextField()),
            ],
        ),
    ]
