# Generated by Django 5.1.5 on 2025-01-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom1', models.CharField(max_length=100)),
                ('cognom2', models.CharField(max_length=100)),
                ('correu', models.EmailField(max_length=254, unique=True)),
                ('curs', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('professor', 'Professor'), ('alumne', 'Alumne')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Alumnat',
        ),
        migrations.DeleteModel(
            name='Professorat',
        ),
    ]
